'use client';
import React, { useCallback, useEffect, useState } from 'react';
import { AdminLayout } from '@/components/AdminLayout'; import { Header } from '@/components/Header';
import { DecisionCard } from '@/components/command/DecisionCard'; import { CommandSection } from '@/components/command/CommandSection'; import { CommandEmptyState } from '@/components/command/CommandEmptyState'; import { CommandSkeleton } from '@/components/command/CommandSkeleton'; import { CommandErrorState } from '@/components/command/CommandErrorState';
import type { CommandResponse } from '@/lib/command/types';
const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
const Empty = () => <p className="text-sm text-[#8E948E] font-mono">Nada aqui agora.</p>;
export default function CommandPage() {
  const [data, setData] = useState<CommandResponse | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const response = await fetch('/api/command'); if (!response.ok) throw new Error('Não foi possível montar seu Command.'); setData(await response.json()); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Falha inesperada.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  return <AdminLayout><Header title="Command" subtitle="A melhor próxima hora do seu dia" />{loading ? <CommandSkeleton /> : error ? <CommandErrorState message={error} onRetry={load} /> : data && <div className="space-y-6">{data.decisions.length ? <section><h2 className="sr-only">Três decisões</h2><div className="grid gap-4 lg:grid-cols-3">{data.decisions.slice(0,3).map((decision, index) => <DecisionCard key={decision.workItemId} decision={decision} rank={index + 1} memberships={data.memberships} onChanged={load} />)}</div></section> : <CommandEmptyState />}<div className="grid gap-4 lg:grid-cols-2"><CommandSection title="Receita em risco">{data.revenueAtRisk.length ? data.revenueAtRisk.map(x => <div key={x.projectId} className="flex justify-between gap-3 border-b border-white/10 py-2"><span>{x.projectName}<small className="block text-[#8E948E]">{x.reason}</small></span><strong className="font-mono text-[#44755A]">{money.format(x.amount)}</strong></div>) : <Empty />}</CommandSection><CommandSection title="Bloqueios externos">{data.externalBlockers.length ? data.externalBlockers.map(x => <p key={x.blockerId} className="text-sm py-2">{x.projectName}: {x.description}</p>) : <Empty />}</CommandSection><CommandSection title="Delegar">{data.delegations.length ? data.delegations.map(x => <p key={x.workItemId} className="text-sm py-2">{x.title} → {x.assigneeName}</p>) : <Empty />}</CommandSection><CommandSection title="O que não fazer agora">{data.notNow.length ? data.notNow.map(x => <p key={x.workItemId} className="text-sm py-2">{x.title} <span className="text-[#8E948E]">· {x.reason}</span></p>) : <Empty />}</CommandSection><CommandSection title="Projetos sem atualização">{data.staleProjects.length ? data.staleProjects.map(x => <p key={x.projectId} className="text-sm py-2">{x.projectName} · {x.daysWithoutUpdate} dias</p>) : <Empty />}</CommandSection></div></div>}</AdminLayout>;
}
