'use client';
import React, { useState } from 'react';
import type { CommandDecision } from '@/lib/command/types';

export function DecisionCard({ decision, rank, memberships, onChanged }: { decision: CommandDecision; rank: number; memberships: Array<{ id: string; name: string }>; onChanged: () => void }) {
  const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [deferUntil, setDeferUntil] = useState(''); const [reason, setReason] = useState(''); const [assignee, setAssignee] = useState('');
  const act = async (action: 'START' | 'COMPLETE' | 'DEFER' | 'DELEGATE') => { setSaving(true); setError(''); const payload: any = { workItemId: decision.workItemId, action, reason }; if (action === 'DEFER') { if (!deferUntil || !reason.trim()) { setError('Informe data e motivo para adiar.'); setSaving(false); return; } payload.deferUntil = new Date(deferUntil).toISOString(); } if (action === 'DELEGATE') { if (!assignee) { setError('Selecione um responsável.'); setSaving(false); return; } payload.assigneeMembershipId = assignee; } const response = await fetch('/api/command', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); if (!response.ok) { const data = await response.json(); setError(data.error || 'Não foi possível registrar a decisão.'); setSaving(false); return; } setSaving(false); onChanged(); };
  return <article data-testid="command-decision" className="card-custom p-5 flex flex-col gap-4 border-[#335943]/40"><div className="flex justify-between"><span className="font-mono text-xs text-[#44755A]">DECISÃO {rank}</span><strong className="font-mono text-2xl text-[#F2F2ED]">{decision.score}</strong></div><div><p className="text-xs text-[#AEB4AE] font-mono">{decision.projectName}</p><h2 className="font-display text-lg font-bold">{decision.title}</h2></div><p className="text-xs font-mono text-[#AEB4AE]">{decision.estimatedMinutes ? `${decision.estimatedMinutes} min` : 'tempo aberto'} · {decision.dueAt ? new Date(decision.dueAt).toLocaleDateString('pt-BR') : 'sem prazo'}</p><details><summary className="cursor-pointer text-xs text-[#44755A] font-mono">Por que agora</summary><ul className="mt-2 text-xs text-[#AEB4AE]">{decision.explanation.map(x => <li key={x}>{x}</li>)}</ul></details><div className="grid grid-cols-2 gap-2"><button disabled={saving} className="btn-custom btn-custom-primary" onClick={() => act('START')}>Começar</button><button disabled={saving} className="btn-custom" onClick={() => act('COMPLETE')}>Concluir</button></div><div className="grid gap-2"><label className="text-xs font-mono">Adiar para<input type="datetime-local" className="w-full bg-[#050505] border border-white/10 p-2" value={deferUntil} onChange={e => setDeferUntil(e.target.value)} /></label><label className="text-xs font-mono">Motivo<input className="w-full bg-[#050505] border border-white/10 p-2" value={reason} onChange={e => setReason(e.target.value)} /></label><button disabled={saving} className="btn-custom" onClick={() => act('DEFER')}>Adiar</button><label className="text-xs font-mono">Delegar para<select className="w-full bg-[#050505] border border-white/10 p-2" value={assignee} onChange={e => setAssignee(e.target.value)}><option value="">Selecione</option>{memberships.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><button disabled={saving} className="btn-custom" onClick={() => act('DELEGATE')}>Delegar</button></div>{error && <p role="alert" className="text-xs text-red-400">{error}</p>}</article>;
}
